export enum listActions {
  FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE"
}

export enum authActions {
  LOGOUT = "LOGOUT"
}

export enum playerActions {
  SET_AUDIO = "SET_AUDIO",
  PLAY_AUDIO = "PLAY_AUDIO",
  PAUSE_AUDIO = "PAUSE_AUDIO",
  STOP_AUDIO = "STOP_AUDIO"
}

export enum userActions {
  GET_USER_REQUEST = "GET_USER_REQUEST",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAILURE = "GET_USER_FAILURE"
}

export enum resourceActions {
  GET_RESOURCES_REQUEST = "GET_RESOURCES_REQUEST",
  GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS",
  GET_RESOURCES_FAILURE = "GET_RESOURCES_FAILURE",

  GET_RESOURCE_REQUEST = "GET_RESOURCE_REQUEST",
  GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS",
  GET_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE",

  ADD_RESOURCE_REQUEST = "ADD_RESOURCE_REQUEST",
  ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS",
  ADD_RESOURCE_FAILURE = "ADD_RESOURCE_FAILURE",

  UPD_RESOURCE_REQUEST = "UPD_RESOURCE_REQUEST",
  UPD_RESOURCE_SUCCESS = "UPD_RESOURCE_SUCCESS",
  UPD_RESOURCE_FAILURE = "UPD_RESOURCE_FAILURE",

  DEL_RESOURCE_REQUEST = "DEL_RESOURCE_REQUEST",
  DEL_RESOURCE_SUCCESS = "DEL_RESOURCE_SUCCESS",
  DEL_RESOURCE_FAILURE = "DEL_RESOURCE_FAILURE"
}

export enum mediaActions {
  GET_MEDIA_REQUEST = "GET_MEDIA_REQUEST",
  GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS",
  GET_MEDIA_FAILURE = "GET_MEDIA_FAILURE",

  GET_MEDIA_RESOURCES_REQUEST = "GET_MEDIA_RESOURCES_REQUEST",
  GET_MEDIA_RESOURCES_SUCCESS = "GET_MEDIA_RESOURCES_SUCCESS",
  GET_MEDIA_RESOURCES_FAILURE = "GET_MEDIA_RESOURCES_FAILURE",

  UPD_MEDIA_RESOURCE_REQUEST = "UPD_MEDIA_RESOURCE_REQUEST",
  UPD_MEDIA_RESOURCE_SUCCESS = "UPD_MEDIA_RESOURCE_SUCCESS",
  UPD_MEDIA_RESOURCE_FAILURE = "UPD_MEDIA_RESOURCE_FAILURE",

  ADD_MEDIA_REQUEST = "ADD_MEDIA_REQUEST",
  ADD_MEDIA_SUCCESS = "ADD_MEDIA_SUCCESS",
  ADD_MEDIA_FAILURE = "ADD_MEDIA_FAILURE",

  DEL_MEDIA_REQUEST = "DEL_MEDIA_REQUEST",
  DEL_MEDIA_SUCCESS = "DEL_MEDIA_SUCCESS",
  DEL_MEDIA_FAILURE = "DEL_MEDIA_FAILURE"
}

export enum imagesActions {
  ADD_IMAGE_REQUEST = "ADD_IMAGE_REQUEST",
  ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS",
  ADD_IMAGE_FAILURE = "ADD_IMAGE_FAILURE",

  DEL_IMAGE_REQUEST = "DEL_IMAGE_REQUEST",
  DEL_IMAGE_SUCCESS = "DEL_IMAGE_SUCCESS",
  DEL_IMAGE_FAILURE = "DEL_IMAGE_FAILURE"
}
