name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build Backend
        run: |
          cd backend/
          npm install
          npm run build

      - name: Build Frontend
        run: |
          cd frontend/
          npm install
          npm run build

      - name: Test Deployment
        run: npm run test
        
      - name: Deploy to Staging
        uses: easingthemes/ssh-deploy@v2.2.6
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.REMOTE_USER }}
          server-ip: ${{ secrets.SERVER_IP }}
          local-path: './'
          server-path: '/var/www/html/staging'
          args: '-rltgoDzvO --no-p --del'