name: Build and Deploy

env:
  CI: false

on:
  push:
    branches:
      - main
      - dev-ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build Backend
        run: |
          cd backend/
          npm install

      - name: Build Frontend
        run: |
          cd frontend/
          npm install
          npm run build --no-warnings

      - name: Test Deployment
        run: npm run test

      - name: Deploy 
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'beegarden'
          heroku_email: 'vovchykhalamaha@gmail.com'
          branch: 'dev-ci'

      # - name: Deploy to Staging
      #   uses: easingthemes/ssh-deploy@v2.2.6
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     remote-user: ${{ secrets.REMOTE_USER }}
      #     server-ip: ${{ secrets.SERVER_IP }}
      #     local-path: './'
      #     server-path: '/var/www/html/staging'
      #     args: '-rltgoDzvO --no-p --del'