name: Coverage

on: push

jobs:
  Run-Code-Coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      
      - name: Build Frontend
        run: |
          cd frontend/
          npm install
          npm run build --no-warnings

      - name: Run tests
        run: |
          cd frontend/
          npm run test
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}