name: Coverage

on: push

jobs:
  Run-Code-Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Build Frontend
        run: |
          cd frontend/
          npm install
          npm run build --no-warnings

      - name: Run tests
        run: |
          cd frontend/
          npm run test
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}